config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  resources :accesses, only: [:new, :create, :destroy]
  resources :chapters, only: :show do
    resources :missions, only: [:new, :create]
  end
  resources :flashcards, only: :destroy
  resources :profiles, only: [:new, :create]
  resources :missions, only: [:show, :destroy, :edit, :update] do
    resources :flashcards, only: [:create]
    member do
      get :play
    end
  end
  resources :rooms, only: [:new, :create, :destroy]
  resources :rooms, only: [:show] do
    resources :chapters, only: [:new, :create]
  end
  resources :subjects, only: [:new, :create]
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :subject
  belongs_to :user
  has_many :chapters, dependent: :destroy
  has_many :accesses, dependent: :destroy

  validates :subject_id, presence: true
  validates :user_id, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def show
    @room = Room.find(params[:id])
    authorize @room
    @chapters = @room.chapters
    # Select access linked to room to give ability to quit room
    @access = @room.accesses.where(user_id: current_user.id)[0]
  end

  def new
    @subjects = current_user.subjects
    @room = Room.new
    authorize @room
    @room.level = ""
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    authorize @room
    @room.save
    if @room.save
      # Create a new access (W/out user intervention)
        @access = Access.new
        @access.user = current_user
        @access.room = @room
        @access.save

      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    @room = Room.find(params[:id])
    authorize @room
    @room.destroy

    redirect_to dashboard_path
  end

  private

  def room_params
    params.require(:room).permit(:level, :subject_id)
  end
end

app/views/rooms/new.html.erb
<div class="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8 bg-gray-50 p-5 lg:p-8 rounded-xl shadow-lg">
    <div>
      <h2 class="text-center text-3xl font-extrabold text-gray-900">
        Créer une nouvelle classe
      </h2>

    </div>
    <%= simple_form_for [@room] do |f| %>
      <div class="rounded-md shadow-sm -space-y-px form-inputs">
        <div>
          <label for="room_id" class="sr-only">Niveau</label>
          <%= f.input :level,
                      label: 'Niveau',
                      placeholder: 'Exemple : 4e ou Terminale S',
                      class: "bg-yellow appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
          <%= f.association :subject,
                            collection: @subjects,
                            include_blank: false,
                            label: 'Matière',
                            class: "relative w-full bg-white border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :submit,
                      'Créer la classe',
                      class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-900 hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<body class="body">
  <div class="row">
    <div class="col-md-2">
      <%= render 'shared/sidebar' %>
    </div>
    <div class="col-md-10 principal-content">
      <div class="d-flex justify-between my-5">
        <% if current_user.teacher? %>
          <div class="room-info">
            <h2 class="mx-3 mb-2"><strong>Niveau : </strong><%= @room.level %> </h2>
            <h3 class="mx-3"><strong>Identifiant de la classe : </strong><%= @room.id %> </h3>
          </div>
        <% else %>
          <div class="room-info">
            <h2 class="mx-3 mb-2"><strong><%= @room.subject.name %></strong></h2>
            <% if @room.user == current_user %>
              <h3 class="mx-3">Vous avez créé cette matière.</h3>
            <% else %>
              <h3 class="mx-3"><strong>Enseignant : </strong><%= @room.user.profile.gender %>. <%= @room.user.profile.last_name %></h3>
            <% end %>
          </div>
        <% end %>

        <div class="relative inline-block text-left mr-4">
          <div>
            <button id="room-options-dropdown-button" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2.5 bg-white text-sm font-medium text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500" id="options-menu" aria-haspopup="true" aria-expanded="true">
              Options
              <!-- Heroicon name: chevron-down -->
              <svg class="-mr-1 ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>

          <!--
            Dropdown panel, show/hide based on dropdown state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div id="room-options-dropdown-panel" class="hidden origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
            <% if @room.user == current_user %>
              <div class="py-1">
                <%= link_to "Nouveau chapitre", new_room_chapter_path(@room), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900" %>
              </div>
            <% end %>
            <div class="py-1">
              <% if policy(@room).destroy? %>
                <div class="py-1">
                  <%= link_to "#{current_user.teacher ? 'Supprimer la classe' : 'Supprimer la matière'}",
                              room_path(@room),
                              method: :delete,
                              data: { confirm: "Êtes-vous certain.e de vouloir supprimer cette #{current_user.teacher ? 'classe' : 'matière'} ?" },
                              class: "block px-4 py-2 text-sm text-red-700 hover:bg-red-100 hover:text-red-900" %>
                </div>
              <% elsif policy(@access).destroy? %>
                <div class="py-1">
                  <%= link_to "Quitter la classe",
                              access_path(@access),
                              method: :delete,
                              data: { confirm: "Êtes-vous certain.e de vouloir quitter cette classe ?" },
                              class: "block px-4 py-2 text-sm text-red-700 hover:bg-red-100 hover:text-red-900" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <% @chapters.each do |chapter| %>
          <div class="chapter mt-4">
            <div class="flex items-end">
              <h3><%= chapter.name %></h3>
              <% if @room.user == current_user %>
                <%= link_to new_chapter_mission_path(chapter) do %>
                  <div class= "flex items-center ml-4 mb-0.5 font-small text-white opacity-30 hover:opacity-50 hover:no-underline transition duration-300 ease-in-out">
                    <svg class="h-5 w-5 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                    Ajouter une mission
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="container flex flex-wrap">
              <% chapter.missions.each do |mission| %>
              <!-- If teacher, click on FC to go to edit view -->
                <% if current_user.teacher? %>
                  <%= link_to mission_path(mission) do %>
                    <div class="r-card d-flex mr-3 my-3">
                      <div class="text-center">
                        <h4 class="mb-5"><%= mission.name %></h4>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                <!-- If Student, click on FC to play -->
                  <div class="r-card d-flex mr-3 my-3 relative">
                    <% if policy(mission).show? && !current_user.teacher? %>
                      <%= link_to mission_path(mission) do %>
                        <div class="edit-icon absolute top-2 right-2 opacity-60">
                          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="#d8dffd">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                          </svg>
                        </div>
                      <% end %>
                    <% end %>
                    <%= link_to play_mission_path(mission) do %>
                      <div class="text-center">
                        <h4 class="mb-5 w-full h-full"><%= mission.name %></h4>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>