config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  resources :accesses, only: [:new, :create, :destroy]
  resources :chapters, only: :show do
    resources :missions, only: [:new, :create]
  end
  resources :flashcards, only: :destroy
  resources :profiles, only: [:new, :create]
  resources :missions, only: [:show, :destroy, :edit, :update] do
    resources :flashcards, only: [:create]
    member do
      get :play
    end
  end
  resources :rooms, only: [:new, :create, :destroy]
  resources :rooms, only: [:show] do
    resources :chapters, only: [:new, :create]
  end
  resources :subjects, only: [:new, :create]
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :chapter
  belongs_to :user

  has_many :flashcards, dependent: :destroy

  validates :name, presence: true
  validates :chapter_id, presence: true
  validates :user_id, presence: true
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_chapter, only: [:new, :create]
  before_action :set_mission, only: [:play, :edit, :update, :destroy]

  def show
    @mission = Mission.find(params[:id])
    @chapter = @mission.chapter
    authorize @mission
    @flashcard = Flashcard.new
    @flashcards = @mission.flashcards

    # Set created date to European format
    @date = @mission.created_at
    @creation_date = "#{@date.day}.#{@date.month}.#{@date.year}"
  end

  def new
    @mission = Mission.new
    @mission.chapter = @chapter
    authorize @mission
  end

  def create
    @mission = Mission.new(mission_params)
    @mission.user = current_user
    @mission.chapter = @chapter
    authorize @mission
    @mission.save
    if @mission.save
      redirect_to mission_path(@mission)
    else
      render :new
    end
  end

  def play
    @chapter = @mission.chapter
    authorize @mission
    @flashcards = @mission.flashcards
  end

  def edit
    authorize @mission
  end

  def update
    authorize @mission
    @mission.update(mission_params)

    redirect_to mission_path(@mission)
  end

  def destroy
    authorize @mission
    @chapter = @mission.chapter
    @mission.destroy
    redirect_to room_path(@chapter.room)
    flash[:notice] = "La mission a bien été supprimée"
  end

  private

  def set_chapter
    @chapter = Chapter.find(params[:chapter_id])
  end

  def set_mission
    @mission = Mission.find(params[:id])
  end

  def mission_params
    params.require(:mission).permit(:name)
  end
end

app/views/missions/edit.html.erb
<div class="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8 bg-gray-50 p-5 lg:p-8 rounded-xl shadow-lg">
    <div>
      <h2 class="text-center text-3xl font-extrabold text-gray-900">
        Modifier la mission
      </h2>

    </div>
    <%= simple_form_for [@mission] do |f| %>
      <div class="rounded-md shadow-sm -space-y-px form-inputs">
        <div>
          <label for="room_id" class="sr-only">Nom</label>
          <%= f.input :name,
                      label: 'Nom',
                      placeholder: 'Nom de la leçon',
                      class: "bg-yellow appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :submit,
                      'Enregistrer',
                      class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-900 hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/missions/new.html.erb
<div class="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8 bg-gray-50 p-5 lg:p-8 rounded-xl shadow-lg">
    <div>
      <h2 class="text-center text-3xl font-extrabold text-gray-900">
        Créer une nouvelle mission
      </h2>

    </div>
    <%= simple_form_for [@chapter, @mission] do |f| %>
      <div class="rounded-md shadow-sm -space-y-px form-inputs">
        <div>
          <label for="room_id" class="sr-only">Niveau</label>
          <%= f.input :name,
                      label: 'Nom',
                      placeholder: 'Nom de la leçon',
                      class: "bg-yellow appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :submit,
                      'Enregistrer',
                      class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-900 hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/missions/play.html.erb
<div class="-mt-7 absolute">
  <%= link_to room_path(@chapter.room) do %>
    <div id="return-top" class= "w-full inline-flex justify-center items-center rounded-md shadow-sm px-3 py-2.5 bg-white text-base font-small text-gray-700 hover:text-pink-800 hover:bg-gray-800 hover:no-underline transition duration-300 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
      <svg class="h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
      </svg><%= @chapter.subject.name %>
    </div>
  <% end %>
</div>

<div class="all-flashcards">
  <% @flashcards.each_with_index do |flashcard, index| %>

    <div class="flashcard <%=index == 0 ? 'block' : 'hidden' %>">
      <div class="flashcard-side block sm:mt-10 w-1/2 mx-auto my-1/4">
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="py-3 bg-white sm:p-6">
            <h3 class="mb-3 text-2xl font-medium text-gray-700"><%= @mission.name %></h3>
            <div class="mb-3">
              <label for="first_name" class="block text-lg font-medium text-gray-700">Question :</label>
              <p class="text-lg text-gray-900 subpixel-antialiased font-semibold"><%= flashcard.question %></p>
            </div>

            <label for="first_name" class="block text-lg font-medium text-gray-700">Votre réponse :</label>
            <textarea name="student_answer" id="student_answer" cols="30" rows="5" autocomplete="off" class="p-2 bg-gray-100 border-2 border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-blue-900 mt-1 block w-full sm:text-sm rounded-md"></textarea>
          </div>
          <div class="px-3 py-2 bg-gray-50 text-right sm:px-3">
             <button type="button" id ="<%= index == 0 ? 'active' : 'unactive' %>" class="flip-card-front-button w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
              Voir la réponse
            </button>
          </div>
        </div>
      </div>


      <div class="flashcard-side hidden sm:mt-10 w-1/2 mx-auto my-1/4">
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="py-3 bg-white sm:p-6">
            <h3 class="mb-3 text-2xl font-medium text-gray-700"><%= @mission.name %></h3>
            <div class="mb-3">
              <label for="first_name" class="block text-lg font-medium text-gray-700">Question :</label>
              <p class="text-lg text-gray-900 subpixel-antialiased font-semibold"><%= flashcard.question %></p>
            </div>
            <div class="mb-1">
              <label for="first_name" class="block text-lg font-medium text-gray-700">Réponse :</label>
              <p class="text-lg text-gray-900 subpixel-antialiased font-semibold"><%= flashcard.answer %></p>
            </div>
          </div>
          <div class="px-4 py-3 bg-gray-50 text-left sm:p-3">
           <label for="first_name" class="block text-lg font-medium text-gray-700">Votre réponse :</label>
           <p class="insert-answer-here text-lg text-gray-800 subpixel-antialiased font-semibold"></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flex justify-evenly mt-4 w-1/2 mx-auto">
  <button type="button" id="correct" class="hidden w-full inline-flex justify-center rounded-md shadow-sm px-4 py-2 bg-green-600 text-base font-medium text-white hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
    Je le savais
  </button>
  <button type="button" id="incorrect" class="hidden w-full inline-flex justify-center rounded-md shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
    Je ne le savais pas
  </button>
</div>
<div class="flex justify-evenly mt-3 w-1/2 mx-auto">
  <%= link_to room_path(@chapter.room) do %>
    <div id="return" class= "hidden w-full inline-flex justify-center items-center rounded-md shadow-sm px-4 py-3 bg-white text-base font-medium text-gray-700 hover:text-pink-800 hover:bg-gray-800 hover:no-underline transition duration-300 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
      <svg class="h-5 w-5 mr-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
      </svg><%= "Retour à la page #{@chapter.subject.name}" %>
    </div>
  <% end %>
</div>

app/views/missions/show.html.erb
<div class="row">
  <div class="col-md-2">
    <%= render 'shared/sidebar' %>
  </div>
  <div class="col-md-10 principal-content">
    <div class="my-2 -ml-3 mr-4 flex justify-between">
      <%= link_to room_path(@chapter.room) do %>
        <div id="return-top" class= "w-full inline-flex justify-center items-center rounded-md shadow-sm px-3 py-2.5 bg-white text-base font-small text-gray-700 hover:text-pink-800 hover:bg-gray-800 hover:no-underline transition duration-300 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
          <svg class="h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg><%= @chapter.subject.name %>
        </div>
      <% end %>

      <div class="relative inline-block text-left mr-4">
        <div>
          <button id="room-options-dropdown-button" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2.5 bg-white text-sm font-medium text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500" id="options-menu" aria-haspopup="true" aria-expanded="true">
            Options
            <!-- Heroicon name: chevron-down -->
            <svg class="-mr-1 ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>

        <!--
          Dropdown panel, show/hide based on dropdown state.

          Entering: "transition ease-out duration-100"
            From: "transform opacity-0 scale-95"
            To: "transform opacity-100 scale-100"
          Leaving: "transition ease-in duration-75"
            From: "transform opacity-100 scale-100"
            To: "transform opacity-0 scale-95"
        -->
        <div id="room-options-dropdown-panel" class="hidden origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
          <div class="py-1">
            <%= link_to "Editer la mission", edit_mission_path(@mission), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900" %>
          </div>
          <div class="py-1">
            <div class="py-1">
              <%= link_to "Supprimer la mission",
                          mission_path(@mission),
                          method: :delete,
                          data: { confirm: "Voulez vous supprimer cette mission ?" },
                          class: "block px-4 py-2 text-sm text-red-700 hover:bg-red-100 hover:text-red-900" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mission-info-box flex justify-between mt-5 pr-6">
      <div class="mission-info-box-text">
        <h1 class="text-5xl mb-4"><%= @mission.name %></h1>
        <h3 class="mb-1 text-2xl font-medium">Créée le : <%= @creation_date %></h3>
        <h3 class="mb-1 text-2xl font-medium">Chapitre : <%= @chapter.name %></h3>
      </div>
    </div>

    <div class="new-flasgcard-form mt-15 sm:mt-10 width-98">
        <%= simple_form_for( [@mission, @flashcard], remote: true, class: "mt-5 md:mt-2") do |f| %>
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="py-3 bg-white sm:p-6">
            <h3 class="mb-3 text-2xl font-medium text-gray-700">Ajouter une Flashcard</h3>
            <div class="flex">
              <div class="flex-grow mx-4">
                <label for="first_name" class="block text-lg font-medium text-gray-700">Question*</label>
                <%= f.input :question, label: false, error: 'Veuillez renseigner une question', class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border-gray-300 rounded-md" %>
              </div>

              <div class="flex-grow mx-4">
                <label for="first_name" class="block text-lg font-medium text-gray-700">Réponse*</label>
                <%= f.input :answer, label: false, error: 'Veuillez renseigner une réponse', class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border-gray-300 rounded-m" %>
              </div>
            </div>
          </div>
          <div class="px-3 py-2 bg-gray-50 text-right sm:px-6">
            <%= f.button :submit, 'Enregistrer', id: "flashcard-save-button" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="hidden sm:block width-98" aria-hidden="true">
      <div class="py-5">
        <div class="border-t border-gray-200"></div>
      </div>
    </div>

    <div class="width-98">
      <h3 class="mb-3 text-2xl font-medium">Flashcards enregistrées :</h3>
      <div class="flashcard-table">
        <div class="flex flex-col">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                    <tr>
                      <th scope="col" class="relative px-6 py-3">
                        <span class="sr-only">Number</span>
                      </th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Question
                      </th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Réponse
                      </th>
                      <th scope="col" class="relative px-6 py-3">
                        <span class="sr-only">Edit</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody class="bg-white divide-y divide-gray-200">
                    <% i = 0 %>
                    <% @flashcards.each do |flashcard| %>
                    <% i += 1 %>
                      <tr>
                        <td class="px-6 py-3 whitespace-nowrap text-sm text-gray-500">
                          <%= i %>
                        </td>
                        <td class="px-6 py-3 whitespace-wrap">
                          <div class="text-sm text-gray-900"><%= flashcard.question %></div>
                        </td>
                        <td class="px-6 py-3 whitespace-wrap">
                          <div class="text-sm text-gray-900"><%= flashcard.answer %></div>
                        </td>
                        <td class="px-2 py-3 whitespace-nowrap text-right text-sm font-medium">
                          <div class="flex items-center mr-3">
                            <a href="#" class="text-blue-900 hover:text-blue-800">Editer</a>
                            <%= link_to(flashcard_path(flashcard),
                            method: :delete,
                            data: { confirm: "Voulez vous supprimer cette flashcard ?" },
                            remote: true) do %>
                              <svg class="h-5 w-5 ml-5 text-red-700" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                              </svg>
                            <% end %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>